on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  keeper-ziren:
    name: Keeper ZKVM Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25
        cache: false

    - name: Install cross toolchain for MIPS
      run: |
        apt-get update
        apt-get -yq --no-install-suggests --no-install-recommends install gcc-mipsel-linux-gnu libc6-dev-mipsel-cross

    - name: Build keeper with ziren tag (mipsle)
      run: |
        go run build/ci.go install -static -arch mipsle -os linux -cc mipsel-linux-gnu-gcc -tags ziren -dlgo ./cmd/keeper
      env:
        GOMIPS: "softfloat"
